[package]
name = "arrise_macro"
version = "0.0.0"
authors = ["melvdl <hansw533@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.8"
itertools = "0.12.1"
proc-macro2 = "1.0.79"
quote = "1.0.36"
syn = { version = "2.0.58" }
